version: "3.9"

services:
  backend:
    env_file:
      - ../.env.dev
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../.dev-storage:/data/artifacts

  frontend:
    env_file:
      - ../.env.dev
    ports:
      - "5173:5173"
    volumes:
      - ..:/app
      - /app/node_modules

  postgres:
    env_file:
      - ../.env.dev
    ports:
      - "5432:5432"

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    profiles: ["optional-security"]
    ports:
      - "8080:8080"

  kali:
    image: kalilinux/kali-rolling
    profiles: ["optional-security"]
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
